[project]
name = "aliqa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "projectw789", email = "projectw789@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.14.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
aliqa = "aliqa:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
